# Generated by Django 5.2.4 on 2025-07-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('time_life', models.DateTimeField()),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
