# Generated by Django 5.2.4 on 2025-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpaste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('base', 'NotProgramLanguage')], default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_life',
            field=models.DateTimeField(verbose_name='Время жизни'),
        ),
    ]
