# Generated by Django 5.2.4 on 2025-07-31 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpaste', '0002_post_author_post_language_post_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publicity',
            field=models.BooleanField(default=False, verbose_name='Публичный пост'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Вставьте ваш текст здесь...', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('plain', 'Обычный текст'), ('py', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript')], default=None, max_length=100, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_life',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 30, 14, 14, 34, 222837), verbose_name='Время жизни'),
        ),
    ]
